version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/my-app
permissions:
  - object: /var/www/html/my-app/
    pattern: "**"
    owner: ec2-user
    group: apache
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
