version: 0.2

phases:
  install:
    runtime-versions:
      ubuntu:latest
    commands:
      - echo Installing dependencies...
      - sudo yum update
      - sudo yum install gcc-c++ make
      - sudo curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
      - sudo yum install nodejs
      - npm install
      - sudo yum update
  build:
    commands:
      - echo started Building app on 'date'
      - cp * /home/ec2-user/
      - npm run build
  post_build:
    commands:
      - echo configuring node and npm...



