version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - sudo yum update -y
      - sudo yum install gcc-c++ make -y
      - sudo curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
      - sudo yum install nodejs -y
      - sudo yum update -y
  build:
    commands:
      - echo started Building app on 'date'
      - cd /home/ec2-user/QSoln
      - npm install
      - npm run build
      - npm run
      - npm start
  post_build:
    commands:
      - echo configuring node and npm...



